### ISSUE TITLE
Disable Physics for Magnebot?

### ISSUE THREAD

**Issue by nnsriram97** [alters-mit/magnebot#12]
Hey @alters-mit, I would like to disable the physics for magnebot and I'm wondering if there are commands in the tdw API that would help me achieve that. Firstly, if I would like to move/rotate the robot I would want to teleport it to the destination without physics. This should also teleport the objects held by the robot. Similarly, in order to grasp some objects I was wondering if I could disable the physics and attach objects to one of the magnebot's arms based on object id. Thanks!

**Comment by alters-mit** [comment]
@nnsriram97 We aren't planning to add a non-physics option to the Magnebot API. However, you can create it yourself with low-level TDW commands:

* Disable physics with [`simulate_physics`](https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#simulate_physics)
* Move and rotate the robot with [`teleport_object`](https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#teleport_object) and [`rotate_object_by`](https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#rotate_object_by) (The Magnebot is an object with ID `0`)
* "Pick up" and "put down" objects with `teleport_object`, `rotate_object_by`, and `rotate_object_to` https://github.com/threedworld-mit/tdw/blob/master/Documentation/api/command_api.md#rotate_object_to.

Unfortunately, we _can't_ implement a non-physics arm articulation API; this isn't allowed in the backend physics engine. It is also impossible to toggle physics off for some actions (such as movement) and enable physics for other actions (such as arm articulation).

Let me know if that helps or if you have other questions.

**Comment by nnsriram97** [comment]
Thanks @alters-mit, I could implement Magnebot without physics, based on `teleport_robot` command. I will close this issue and re-open it later if I have any questions
